receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

  fluentforward:
    endpoint: 0.0.0.0:8006

  filelog/laravel:
    include:
      - /var/log/montry/web/*.log
    include_file_path: true
    start_at: end
    operators:
      - type: json_parser
        parse_from: body

processors:
  batch:
    timeout: 5s
    send_batch_size: 1024

  resource/montry_logs:
    attributes:
      - key: service.namespace
        action: upsert
        value: montry

exporters:
  prometheus:
    endpoint: 0.0.0.0:8889

  otlp/tempo:
    endpoint: tempo:4317
    tls:
      insecure: true

  loki:
    endpoint: http://loki:3100/loki/api/v1/push

  debug:
    verbosity: basic

service:
  telemetry:
    metrics:
      address: 0.0.0.0:8888

  pipelines:
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [prometheus, debug]

    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlp/tempo, debug]

    logs:
      receivers: [otlp, fluentforward, filelog/laravel]
      processors: [resource/montry_logs, batch]
      exporters: [loki, debug]
